version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aura-recommendation-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/workspace/data
      - ./backend/models:/workspace/models
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: aura-recommendation-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
